version: '3.7'
services:

  db:
    image: mongo
    restart: always
    container_name: "judgebot-db"
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - judgebot:/data/db

  bot:
    container_name: Judgebot
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./config/config.json
        target: /config/config.json
    restart: always
    env_file:
      - .env
    depends_on:
      - db

volumes:
  judgebot: